# Generated by Django 3.2.5 on 2021-08-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=200)),
                ('fecha_creacion_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_registro', models.DateTimeField(auto_now=True)),
                ('cant_imagenes', models.IntegerField()),
                ('CI', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tmp')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconocimiento_facial.persona')),
            ],
        ),
    ]
