# Generated by Django 3.2.5 on 2021-08-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['nombre']},
        ),
    ]
