# Generated by Django 3.2.5 on 2021-08-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0002_alter_persona_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='files')),
            ],
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={},
        ),
        migrations.RemoveField(
            model_name='persona',
            name='cant_imagenes',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.AddField(
            model_name='personaimagen',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen', to='reconocimiento_facial.persona'),
        ),
    ]
