# Generated by Django 3.2.5 on 2021-08-23 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0003_auto_20210818_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconocimiento_facial.persona')),
            ],
        ),
        migrations.DeleteModel(
            name='PersonaImagen',
        ),
    ]
