# Generated by Django 3.2.5 on 2021-08-24 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0004_auto_20210823_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/reconocimiento_facial/<django.db.models.query_utils.DeferredAttribute object at 0x000001EB4C4FB6D0>')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconocimiento_facial.persona')),
            ],
        ),
        migrations.DeleteModel(
            name='PersonaImage',
        ),
    ]
