# Generated by Django 3.2.5 on 2021-08-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0007_auto_20210823_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='image',
            field=models.ImageField(upload_to='media/reconocimiento_facial/<django.db.models.query_utils.DeferredAttribute object at 0x0000025334F8B6D0>'),
        ),
    ]
