# Generated by Django 3.2.5 on 2021-09-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0008_alter_imagen_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AlterField(
            model_name='imagen',
            name='image',
            field=models.ImageField(upload_to='tmp/'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='departamento',
            field=models.CharField(choices=[('Software', 'Software'), ('AudioVisual', 'AudioVisual'), ('Taller', 'Taller')], max_length=100),
        ),
    ]
