# Generated by Django 3.2.5 on 2021-09-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0009_auto_20210904_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagenes_en_dataset',
            field=models.PositiveIntegerField(default='0', editable=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='imagenes_sin_subir',
            field=models.PositiveIntegerField(default='0', editable=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
    ]
