# Generated by Django 3.2.5 on 2021-09-18 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0012_persona_imagenes_en_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembros_del_Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_Entrenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('trabajadores', models.ManyToManyField(through='reconocimiento_facial.Miembros_del_Modelo', to='reconocimiento_facial.Persona')),
            ],
            options={
                'verbose_name_plural': 'Modelos Entrenados',
            },
        ),
        migrations.AddField(
            model_name='miembros_del_modelo',
            name='modelo_entrenado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reconocimiento_facial.modelo_entrenado'),
        ),
        migrations.AddField(
            model_name='miembros_del_modelo',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reconocimiento_facial.persona'),
        ),
    ]
