# Generated by Django 3.2.5 on 2021-09-19 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0013_auto_20210918_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Miembros_del_Modelo',
            new_name='Miembro_del_Modelo',
        ),
    ]
