# Generated by Django 3.2.5 on 2021-09-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0014_rename_miembros_del_modelo_miembro_del_modelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miembro_del_modelo',
            options={'verbose_name_plural': 'Miembros del Modelo'},
        ),
        migrations.AddField(
            model_name='miembro_del_modelo',
            name='CI',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
