# Generated by Django 3.2.5 on 2021-09-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0017_raspberry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raspberry',
            new_name='Raspberry_Camara',
        ),
    ]
