# Generated by Django 3.2.5 on 2021-09-23 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0018_rename_raspberry_raspberry_camara'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raspberry_Camara',
            new_name='Raspberry',
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name_plural': 'Trabajadores del Centro'},
        ),
        migrations.AlterModelOptions(
            name='raspberry',
            options={'verbose_name_plural': 'Raspberrys_Cámaras'},
        ),
    ]
