# Generated by Django 3.2.5 on 2021-09-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0019_auto_20210922_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberry',
            name='id_suscribe',
            field=models.CharField(default=False, editable=False, max_length=50),
        ),
    ]
