# Generated by Django 3.2.5 on 2021-09-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0020_raspberry_id_suscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberry',
            name='id_suscribe',
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
    ]
