# Generated by Django 3.2.5 on 2021-09-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0022_auto_20210928_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberry',
            name='ip_address',
            field=models.GenericIPAddressField(editable=False, null=True),
        ),
    ]
