# Generated by Django 3.2.5 on 2021-10-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0025_remove_raspberry_is_synchronized'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberry',
            name='is_syncronize',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
