# Generated by Django 3.2.5 on 2021-10-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento_facial', '0026_raspberry_is_syncronize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo_entrenado',
            name='nombre',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
